-- Exact SDK sensors; first-pass group selection. See temp.md/MISSION_PRISONBREAK_STATUS.md.
return {
    {name = "cell1_1", region = 32, objective = "OBJ_CELLBLOCK_ENC_1_80F7C409", squads = {
        "SQ_CABAL_ENC1_ANCHOR_1",
        "SQ_CABAL_ENC1_SPECIAL_1_80F7C409",
        "SQ_CABAL_ENC1_SPECIAL_2_80F7C409",
        "SQ_FALLEN_ENC1_FODDER_1",
        "SQ_FALLEN_ENC1_FODDER_2",
        "SQ_FALLEN_ENC1_SPECIAL_2",
        "SQ_FALLEN_ENC1_SPECIAL_3",
        "SQ_FALLEN_ENC1_SPECIAL_4",
        "SQ_FALLEN_ENC1_SPECIAL_5",
    }},
    {name = "cell1_2", region = 32, objective = "OBJ_CELLBLOCK_ENC_2_80F7C409", squads = {
        "SQ_CABAL_ENC2_FODDER_1",
        "SQ_CABAL_ENC2_FODDER_2",
        "SQ_CABAL_ENC2_FODDER_3",
        "SQ_CABAL_ENC2_FODDER_4",
        "SQ_FALLEN_ENC2_FODDER_1_80F7C409",
        "SQ_FALLEN_ENC2_FODDER_2",
        "SQ_FALLEN_ENC2_SPECIAL_1_80F7C409",
        "SQ_FALLEN_ENC2_SPECIAL_2_80F7C409",
    }},
    {name = "cell1_3", region = 32, objective = "OBJ_CELLBLOCK_ENC_3_80F7C409", squads = {
        "SQ_CABAL_ENC3_ANCHOR_1",
        "SQ_CABAL_ENC3_FODDER_1",
        "SQ_CABAL_ENC3_FODDER_2",
        "SQ_CABAL_ENC3_FODDER_3",
        "SQ_CABAL_ENC3_FODDER_4",
        "SQ_FALLEN_ENC3_BLASTER_1",
        "SQ_FALLEN_ENC3_FODDER_1",
        "SQ_FALLEN_ENC3_FODDER_2",
        "SQ_FALLEN_ENC3_FODDER_3",
        "SQ_FALLEN_ENC3_FODDER_4",
        "SQ_FALLEN_ENC3_SPECIAL_1",
        "SQ_FALLEN_ENC3_SPECIAL_2",
    }},
    {name = "cell2_1", region = 32, objective = "OBJ_CELLBLOCK_ENC_1_80F7C5D8", squads = {
        "SQ_CABAL_ENC1_FODDER_1",
        "SQ_CABAL_ENC1_SPECIAL_1_80F7C5D8",
        "SQ_CABAL_ENC1_SPECIAL_2_80F7C5D8",
        "SQ_HIVE_ENC1_ANCHOR_1",
        "SQ_HIVE_ENC1_FODDER_1",
    }},
    {name = "cell2_2", region = 32, objective = "OBJ_CELLBLOCK_ENC_2_80F7C5D8", squads = {
        "SQ_FALLEN_ENC2_FODDER_1_80F7C5D8",
        "SQ_FALLEN_ENC2_SPECIAL_1_80F7C5D8",
        "SQ_FALLEN_ENC2_SPECIAL_2_80F7C5D8",
        "SQ_HIVE_ENC2_ANCHOR_1",
        "SQ_HIVE_ENC2_ANCHOR_2",
        "SQ_HIVE_ENC2_FODDER_1",
        "SQ_HIVE_ENC2_FODDER_2",
        "SQ_HIVE_ENC2_FODDER_3",
        "SQ_HIVE_ENC2_FODDER_4",
        "SQ_HIVE_ENC2_FODDER_5",
        "SQ_HIVE_ENC2_FODDER_6",
    }},
    {name = "cell2_3", region = 32, objective = "OBJ_CELLBLOCK_ENC_3_80F7C5D8", squads = {
        "SQ_HIVE_ENC3_FODDER_1",
        "SQ_HIVE_ENC3_FODDER_5",
        "SQ_HIVE_ENC3_SPECIAL_1",
    }},
    {name = "cell2_4", region = 32, objective = "OBJ_CELLBLOCK_ENC_4", squads = {
        "SQ_CABAL_ENC4_FODDER_1",
        "SQ_CABAL_ENC4_FODDER_2",
        "SQ_FALLEN_ENC4_ANCHOR_1",
        "SQ_FALLEN_ENC4_FODDER_1",
        "SQ_FALLEN_ENC4_FODDER_2",
        "SQ_FALLEN_ENC4_FODDER_3",
        "SQ_FALLEN_ENC4_SPECIAL_1",
        "SQ_HIVE_ENC4_ANCHOR_1",
        "SQ_HIVE_ENC4_FODDER_1",
        "SQ_HIVE_ENC4_FODDER_6",
        "SQ_HIVE_ENC4_FODDER_7",
        "SQ_HIVE_ENC4_FODDER_8",
    }},
    {name = "yard_cabal", region = 32, objective = "OBJ_YARD_CABAL",
      required = {"SQ_YARD_CABAL_BOSS_1"}, required_only = true, squads = {
        "SQ_YARD_CABAL_BOSS_1",
        "SQ_YARD_CABAL_FODDER_1",
        "SQ_YARD_CABAL_FODDER_2",
        "SQ_YARD_CABAL_FODDER_3",
        "SQ_YARD_CABAL_FODDER_4",
        "SQ_YARD_CABAL_FODDER_5",
        "SQ_YARD_CABAL_FODDER_6",
        "SQ_YARD_CABAL_FODDER_7",
        "SQ_YARD_CABAL_SPECIAL_1",
        "SQ_YARD_CABAL_SPECIAL_2",
        "SQ_YARD_CABAL_SPECIAL_3",
    }},
    {name = "yard_fallen_boss", region = 32, objective = "OBJ_YARD_FALLEN",
      required = {"SQ_YARD_FALLEN_BOSS_1"}, required_only = true, squads = {
        "SQ_YARD_FALLEN_BOSS_1",
    }},
    {name = "yard_fallen", region = 32, objective = "OBJ_YARD_FALLEN", squads = {
        "SQ_YARD_FALLEN_FODDER_1",
        "SQ_YARD_FALLEN_FODDER_2",
        "SQ_YARD_FALLEN_FODDER_3",
        "SQ_YARD_FALLEN_FODDER_4",
        "SQ_YARD_FALLEN_FODDER_5",
        "SQ_YARD_FALLEN_FODDER_6",
        "SQ_YARD_FALLEN_FODDER_7",
        "SQ_YARD_FALLEN_FODDER_8",
        "SQ_YARD_FALLEN_FODDER_9",
        "SQ_YARD_FALLEN_FODDER_10",
        "SQ_YARD_FALLEN_MELEE_1",
    }},
    {name = "turret_entry", region = 32, objective = "OBJ_HIVE_80F7C9E4", squads = {
        "SQ_HIVE_BALCONY_1",
        "SQ_HIVE_BALCONY_2",
        "SQ_HIVE_FODDER",
        "SQ_HIVE_FODDER_2_80F7C9E4",
        "SQ_HIVE_PREFIGHT_0_80F7C9E4",
        "SQ_HIVE_PREFIGHT_1_80F7C9E4",
    }},
    {name = "turret_last", region = 32, objective = "OBJ_HIVE_80F7C9E4", squads = {
        "SQ_HIVE_LAST_0",
        "SQ_HIVE_LAST_1",
        "SQ_HIVE_LAST_2",
        "SQ_HIVE_MAJOR_80F7C9E4",
    }},
    -- Authored Petra-to-security vignettes.  Place their actors during Petra's
    -- performance so the player does not watch them pop in at each trigger.
    {name = "hallway_chase", region = 32, squads = {
        "SQ_GUARD_80F7C0C7",
        "SQ_GUARD_1_80F7C0C7",
        "SQ_CENTURION",
        "SQ_LEGIONARY",
    }},
    {name = "train_runover", region = 32, objective = "OBJ_TRAIN_RUNOVER", squads = {
        "SQ_CABAL_FODDER_1_80F7CB79",
        "SQ_CABAL_FODDER_2_80F7CB79",
        "SQ_FALLEN_FODDER_1",
        "SQ_FALLEN_FODDER_2",
    }},
    -- Cayde's bridge performance owns the charging Hive target, the three
    -- Legionaries below it, and the Fallen killed by the follow-up rocket.
    {name = "cayde_bridge", region = 32, squads = {
        "SQUAD_CAYDE",
        "SQUAD_CHARGING_COMBATANT",
        "SQUAD_EXPLODING_COMBATANT_1",
        "SQUAD_EXPLODING_COMBATANT_2",
        "SQUAD_EXPLODING_COMBATANT_3",
        "SQUAD_DYING_FALLEN_1",
        "SQUAD_DYING_FALLEN_2",
        "SQUAD_DYING_FALLEN_3",
    }},
    {name = "security_hive", region = 32, objective = "OBJ_HIVE_80F7C95B", squads = {
        "SQ_HIVE_ANCHOR_0",
        "SQ_HIVE_ANCHOR_1",
        "SQ_HIVE_FODDER_0",
        "SQ_HIVE_FODDER_1",
        "SQ_HIVE_FODDER_2_80F7C95B",
        "SQ_HIVE_FODDER_3",
        "SQ_HIVE_FODDER_4",
        "SQ_HIVE_MAJOR_80F7C95B",
        "SQ_HIVE_PREFIGHT_0_80F7C95B",
        "SQ_HIVE_PREFIGHT_1_80F7C95B",
        "SQ_HIVE_PREFIGHT_2",
        "SQ_HIVE_SUPPORT_0",
        "SQ_HIVE_SUPPORT_1",
    }},
    {name = "security_cabal", region = 32, objective = "OBJ_CABAL", squads = {
        "SQ_CABAL_ANCHOR_0_80F7C95B",
        "SQ_CABAL_ANCHOR_1",
        "SQ_CABAL_BOSS",
        "SQ_CABAL_FODDER_0_80F7C95B",
        "SQ_CABAL_FODDER_1_80F7C95B",
        "SQ_CABAL_FODDER_2_80F7C95B",
        "SQ_CABAL_FODDER_3_80F7C95B",
        "SQ_CABAL_FODDER_4_80F7C95B",
        "SQ_CABAL_PREFIGHT_0",
        "SQ_CABAL_PREFIGHT_1",
        "SQ_CABAL_PREFIGHT_2",
        "SQ_CABAL_SUPPORT_0",
        "SQ_CABAL_SUPPORT_1",
    }},
    -- These are authored control-room actors rather than objective lanes. They
    -- still need explicit placement; leaving them out makes the room empty
    -- even when the preceding security waves are complete.
    {name = "control_room_exploders", region = 32, squads = {
        "SQUAD_EXPLODING_UNIT_1",
        "SQUAD_EXPLODING_UNIT_2",
        "SQUAD_EXPLODING_UNIT_3",
    }},
    {name = "control_room_cayde", region = 32, squads = {
        "SQUAD_CAYDE_1",
    }},
    {name = "wretch_intro", region = 40, objective = "OBJ_WRETCH_INTRO", squads = {
        "SQ_WRETCH_REVEAL_1",
        "SQ_WRETCH_REVEAL_2",
        "SQ_WRETCH_REVEAL_4",
        "SQ_WRETCH_REVEAL_5",
        "SQ_WRETCH_REVEAL_6",
    }},
    {name = "wretch_ambush", region = 40, objective = "OBJ_WRETCH_HIDERS", squads = {
        "SQ_WRETCH_AMBUSH_1",
        "SQ_WRETCH_AMBUSH_10",
        "SQ_WRETCH_AMBUSH_11",
        "SQ_WRETCH_AMBUSH_2",
        "SQ_WRETCH_AMBUSH_3",
        "SQ_WRETCH_AMBUSH_4",
        "SQ_WRETCH_AMBUSH_5",
        "SQ_WRETCH_AMBUSH_6",
        "SQ_WRETCH_AMBUSH_7",
        "SQ_WRETCH_AMBUSH_8",
        "SQ_WRETCH_AMBUSH_9",
    }},
    {name = "wretch_riot", region = 40, objective = "OBJ_WRETCH_RIOT", squads = {
        "SQ_WRETCH_RIOT_1",
        "SQ_WRETCH_RIOT_2",
        "SQ_WRETCH_RIOT_3",
        "SQ_WRETCH_RIOT_4",
        "SQ_WRETCH_RIOT_5",
    }},
    {name = "wretch_final", region = 40, objective = "OBJ_WRETCH_RIOT", squads = {
        "SQ_WRETCH_RIOT_FINAL",
    }},
    {name = "looters", region = 40, objective = "OBJ_VANDAL_LOOTERS", squads = {
        "SQ_VANDAL_LOOTER_1",
        "SQ_VANDAL_LOOTER_2",
        "SQ_VANDAL_LOOTER_3",
    }},
    {name = "catwalk", region = 40, objective = "OBJ_VANDAL_CATWALK", squads = {
        "SQ_VANDAL_CATWALK_1",
        "SQ_VANDAL_CATWALK_2",
    }},
    {name = "vandal_1", region = 40, objective = "OBJ_VANDAL_WAVE_1", squads = {
        "SQ_VANDAL_WAVE_1_1",
        "SQ_VANDAL_WAVE_1_2",
        "SQ_VANDAL_WAVE_1_3",
        "SQ_VANDAL_WAVE_1_4",
        "SQ_VANDAL_WAVE_1_5",
        "SQ_VANDAL_WAVE_1_6",
    }},
    {name = "vandal_2", region = 40, objective = "OBJ_VANDAL_WAVE_2", squads = {
        "SQ_VANDAL_WAVE_2_1",
        "SQ_VANDAL_WAVE_2_2",
        "SQ_VANDAL_WAVE_2_3",
        "SQ_VANDAL_WAVE_2_4",
        "SQ_VANDAL_WAVE_2_5",
    }},
    {name = "vandal_3", region = 40, objective = "OBJ_VANDAL_WAVE_3", squads = {
        "SQ_VANDAL_WAVE_3_1",
        "SQ_VANDAL_WAVE_3_2",
        "SQ_VANDAL_WAVE_3_3",
    }},
    {name = "crawlers", region = 40, objective = "OBJ_CRAWLER_FLOOD", squads = {
        "SQ_CRAWLER_FLOOD_INITIAL_1",
        "SQ_CRAWLER_FLOOD_INITIAL_2",
        "SQ_CRAWLER_FLOOD_INITIAL_3",
    }},
    {name = "crawler_final", region = 40, objective = "OBJ_CRAWLER_FLOOD", squads = {
        "SQ_CRAWLER_FLOOD_FINALE_1",
    }},
    {name = "boss", region = 40, objective = "OBJECTIVE_ABOMINATION", squads = {
        "SQ_ABOMINATION",
    }},
    {name = "boss_support", region = 40, objective = "OBJECTIVE_ABOMINATION", squads = {
        "SQ_VANDAL_RIFLE_0",
        "SQ_VANDAL_RIFLE_1",
        "SQ_VANDAL_RIFLE_2",
        "SQ_VANDAL_RIFLE_3",
        "SQ_VANDAL_RIFLE_4",
        "SQ_VANDAL_RIFLE_5",
        "SQ_VANDAL_RIFLE_6",
        "SQ_VANDAL_RIFLE_7",
    }},
}
